sudo: false

language: node_js

matrix:
  fast_finish: true
  include:
    - node_js: '14'
    - node_js: '12'
    - node_js: '10'

env:
  global:
    - AWS_ACCESS_KEY_ID=AKID
    - AWS_SECRET_ACCESS_KEY=SECRET
    - AWS_REGION=us-east-1
before_install:
  - docker pull localstack/localstack:0.11.5
  - docker run -d --name localstack -p 4569:4569 -e SERVICES=dynamodb --rm localstack/localstack:0.11.5

install: npm install

services:
  - docker
